let data={classes:[],students:[],assignments:[],mistakes:[],seats:[],performances:[]}, settings={}, dashboardClass='', token=localStorage.getItem('token')||'', currentUser=null, seatClass='', seatLesson='', selSeat=null, seatDraftImage='';
const $=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const ROLE_NAMES={admin:'管理员',teacher:'老师',student:'学生'};
const SEAT_TAGS=['积极发言','认真听讲','思考深入','合作良好','进步明显','需要关注'];
async function api(url,opts={}){opts.headers={...(opts.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(url,opts),d=await r.json();if(r.status===401){token='';localStorage.removeItem('token');showAuth()}if(!r.ok)throw Error(d.error||'操作失败');return d}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function showAuth(){$('#auth-screen').classList.add('show')} function hideAuth(){$('#auth-screen').classList.remove('show')}
function setSession(t,u){token=t;localStorage.setItem('token',t);currentUser=u;$('#user-chip').textContent=`${u.realName||u.username} · ${ROLE_NAMES[u.role]||u.role}`;applyRole()}
function applyRole(){const r=currentUser?.role;document.body.classList.toggle('role-student',r==='student');$('#nav-accounts').style.display=r==='admin'?'':'none';if(r==='student'){document.querySelectorAll('.page').forEach(x=>x.classList.remove('show'));$('#student-home').classList.add('show');$('#page-title').textContent='我的错题';$('#subtitle').textContent='老师录入并确认后的错题会显示在这里'}}
function className(id){return data.classes.find(x=>x.id===id)?.name||'未分班'} function studentName(id){return data.students.find(x=>x.id===id)?.name||'未识别学生'}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function lessonLabel(a){const p=[];if(a.date)p.push(a.date);if(a.period)p.push(`第${a.period}节`);p.push(className(a.classId));return p.join(' · ')}
function fillSelect(selector,items,placeholder,fmt=x=>x.name){const el=$(selector);if(!el)return;const old=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option value="${x.id}">${esc(fmt(x))}</option>`).join('');el.value=old}
function render(){
 fillSelect('#student-class',data.classes,'请选择班级');fillSelect('#lesson-class',data.classes,'请选择班级');fillSelect('#analyze-lesson',[...data.assignments].reverse(),'请选择课程',x=>`${lessonLabel(x)} · ${x.title}`);fillSelect('#dashboard-class',data.classes,'全部班级');fillSelect('#mistake-assignment',data.assignments,'请选择分析任务',x=>`${x.title} · ${lessonLabel(x)}`);fillSelect('#mistake-student',data.students,'请选择学生',x=>`${x.name} · ${className(x.classId)}`);
 const aClass={};data.assignments.forEach(a=>aClass[a.id]=a.classId);const classOf=m=>aClass[m.assignmentId]||data.students.find(s=>s.id===m.studentId)?.classId||'';
 const mistakes=dashboardClass?data.mistakes.filter(m=>classOf(m)===dashboardClass):data.mistakes, students=dashboardClass?data.students.filter(s=>s.classId===dashboardClass):data.students;
 $('#class-count').textContent=data.classes.length;$('#student-count').textContent=students.length;$('#mistake-count').textContent=mistakes.length;$('#pending-count').textContent=mistakes.filter(x=>x.status==='pending'||x.errorType==='待老师确认').length;
 const by=k=>mistakes.reduce((a,x)=>{a[x[k]||'待确认']=(a[x[k]||'待确认']||0)+1;return a},{}), kp=by('knowledgePoint'), et=by('errorType');
 const kc=$('#knowledge-chart');kc.className='bar-chart'+(!Object.keys(kp).length?' empty':'');kc.innerHTML=Object.keys(kp).length?Object.entries(kp).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([k,v])=>`<div class="bar" style="height:${Math.max(25,v/Math.max(...Object.values(kp))*190)}px"><span>${v}人</span><label>${esc(k)}</label></div>`).join(''):'暂时还没有错题数据';
 const colors=['#5b4bda','#ee6eaa','#ff9d4d','#48b9ac','#7895e8'], max=Math.max(...Object.values(et),1),tc=$('#type-chart');tc.className='type-chart'+(!Object.keys(et).length?' empty':'');tc.innerHTML=Object.keys(et).length?Object.entries(et).sort((a,b)=>b[1]-a[1]).map(([k,v],i)=>`<div class="type-row"><span>${esc(k)}</span><div class="track"><div class="fill" style="width:${v/max*100}%;background:${colors[i%colors.length]}"></div></div><b>${v}</b></div>`).join(''):'暂时还没有错题数据';
 const freq=Object.values(mistakes.reduce((a,x)=>{const k=x.question||'未填写题目描述';(a[k]??={q:k,n:0,ids:[]}).n++;a[k].ids.push(x.studentId);return a},{})).sort((a,b)=>b.n-a.n).slice(0,5);$('#frequency-table').innerHTML=freq.length?`<div class="row-list">${freq.map(x=>`<div class="item"><div><b>${esc(x.q)}</b><div class="meta">涉及学生：${[...new Set(x.ids)].map(studentName).join('、')}</div></div><span class="tag">${x.n} 条记录</span></div>`).join('')}</div>`:'录入错题后，这里会展示最需要讲解的题目。';
 const todays=data.assignments.filter(a=>a.date===localDate()).sort((a,b)=>(+a.period||99)-(+b.period||99)),ts=$('#today-schedule');ts.className=todays.length?'':'table-empty';ts.innerHTML=todays.length?`<div class="row-list">${todays.map(a=>`<div class="item"><div><b>${a.period?`第${esc(a.period)}节`:'未指定节次'} · ${esc(className(a.classId))}</b><div class="meta">${esc(a.title)}${(a.knowledgePoints||[]).length?' · 知识点：'+esc(a.knowledgePoints.join('、')):''}</div></div></div>`).join('')}</div>`:'今天还没有上课记录，导入作业时选择今天的日期即可显示在这里。';
 $('#class-list').innerHTML=data.classes.length?`<div class="row-list">${data.classes.map(c=>{const ss=data.students.filter(s=>s.classId===c.id);return `<div class="item"><div><b>${esc(c.name)}</b><div class="meta">${esc(c.grade||'未填写年级')} · ${ss.length} 名学生${ss.length?'：'+ss.map(s=>esc(s.name)).join('、'):''}</div></div><button class="danger" onclick="del('classes','${c.id}')">删除</button></div>`}).join('')}</div>`:'请先创建一个班级。';
 $('#assignment-list').innerHTML=data.assignments.length?`<div class="row-list">${[...data.assignments].reverse().map(a=>`<div class="item"><div><b>${esc(a.title)}</b><div class="meta">${esc(lessonLabel(a))}<br>${esc(a.content||'AI 未识别课堂摘要')}<br>知识点：${esc((a.knowledgePoints||[]).join('、')||'待确认')}</div></div></div>`).join('')}</div>`:'导入课堂报告后，每节课的记录会显示在这里。';
 const recent=[...data.mistakes].reverse().slice(0,8);$('#mistake-list').innerHTML=recent.length?`<div class="row-list">${recent.map(m=>`<div class="item"><div><b>${esc(m.question||'未填写题目')}</b><div class="meta">${esc(studentName(m.studentId))} · ${esc(m.knowledgePoint)} · ${esc(m.errorType)}${m.note?'<br>'+esc(m.note):''}</div></div><span class="tag ${m.status==='pending'?'pending':''}">${m.status==='pending'?'待确认':'已确认'}</span><button class="danger" onclick="del('mistakes','${m.id}')">删除</button></div>`).join('')}</div>`:'尚未录入错题。';
}
function seatAt(r,c){return data.seats.find(s=>s.classId===seatClass&&s.row===r&&s.col===c)}
function perfAt(r,c){return data.performances.find(p=>p.classId===seatClass&&(p.assignmentId||'')===seatLesson&&p.row===r&&p.col===c)}
function renderSeats(){
 fillSelect('#seat-class',data.classes,'请选择班级');
 if(!$('#seat-class').value&&data.classes.length)$('#seat-class').value=data.classes[0].id;
 seatClass=$('#seat-class').value;
 const cls=data.classes.find(c=>c.id===seatClass);
 fillSelect('#seat-lesson',data.assignments.filter(a=>a.classId===seatClass).reverse(),'不关联课程',x=>`${lessonLabel(x)} · ${x.title}`);
 seatLesson=$('#seat-lesson').value;
 const map=$('#seat-map');
 if(!cls){map.innerHTML='<div class="table-empty">请先在“班级与学生”创建班级。</div>';return}
 if(document.activeElement!==$('#seat-rows'))$('#seat-rows').value=cls.seatRows||4;
 if(document.activeElement!==$('#seat-cols'))$('#seat-cols').value=cls.seatCols||6;
 const rows=cls.seatRows||4, cols=cls.seatCols||6;
 map.innerHTML=Array.from({length:rows},(_,i)=>i+1).map(r=>`<div class="seat-row" style="grid-template-columns:repeat(${cols},1fr)">`+Array.from({length:cols},(_,j)=>j+1).map(c=>{const seat=seatAt(r,c),perf=perfAt(r,c),stu=seat&&data.students.find(s=>s.id===seat.studentId),hasPerf=perf&&(perf.tags?.length||perf.note||perf.image);return `<button class="seat-cell${stu?'':' empty'}${hasPerf?' has-perf':''}${selSeat&&selSeat.r===r&&selSeat.c===c?' selected':''}" data-r="${r}" data-c="${c}"><span class="seat-idx">${String((r-1)*cols+c).padStart(2,'0')}</span><span class="seat-who">${stu?esc(stu.name):'空位'}</span><span class="seat-flag">${hasPerf?esc(perf.tags?.[0]||'已记录'):''}</span></button>`}).join('')+'</div>').join('');
 map.querySelectorAll('.seat-cell').forEach(b=>b.onclick=()=>selectSeat(+b.dataset.r,+b.dataset.c));
 if(selSeat)renderSeatEditor();
}
function selectSeat(r,c){selSeat={r,c};seatDraftImage='';renderSeats();renderSeatEditor()}
function renderSeatEditor(){
 const {r,c}=selSeat;$('#seat-editor-title').textContent=`第 ${r} 排 · 第 ${c} 列`;$('#seat-editor-body').style.display='grid';
 const seat=seatAt(r,c),perf=perfAt(r,c),tags=perf?.tags||[];
 fillSelect('#seat-student',data.students.filter(s=>s.classId===seatClass),'未安排');$('#seat-student').value=seat?.studentId||'';
 $('#seat-tags').innerHTML=SEAT_TAGS.map(t=>`<button type="button" class="${tags.includes(t)?'active':''}" data-tag="${t}">${t}</button>`).join('');
 $('#seat-tags').querySelectorAll('button').forEach(b=>b.onclick=()=>b.classList.toggle('active'));
 $('#seat-note').value=perf?.note||'';
 $('#seat-work-note').value=perf?.workNote||'';
 renderSeatImage(perf?.image||'');
}
function renderSeatImage(img){$('#seat-image-preview').innerHTML=img?`<div class="img-wrap"><img src="${img}"><button type="button" class="danger" id="seat-image-del">删除</button></div>`:'';if(img)$('#seat-image-del').onclick=()=>{seatDraftImage='__clear__';renderSeatImage('')}}
async function uploadSeatImage(f){try{if(f.size>5*1024*1024)throw Error('图片超过 5MB');const src=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});const res=await api('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:src})});seatDraftImage=res.path;renderSeatImage(res.path);toast('截图已添加，点“保存记录”后生效')}catch(e){toast(e.message)}}
function renderStudent(){const ms=data.mistakes,amap={};data.assignments.forEach(a=>amap[a.id]=a);
 $('#st-mistake-count').textContent=ms.length;$('#st-pending-count').textContent=ms.filter(x=>x.status==='pending').length;
 $('#student-mistake-list').innerHTML=ms.length?`<div class="row-list">${[...ms].reverse().map(m=>{const a=amap[m.assignmentId];return `<div class="item"><div><b>${esc(m.question||'未填写题目')}</b><div class="meta">${a?esc(lessonLabel(a))+'<br>':''}知识点：${esc(m.knowledgePoint)} · ${esc(m.errorType)}${m.note?'<br>'+esc(m.note):''}</div></div><span class="tag ${m.status==='pending'?'pending':''}">${m.status==='pending'?'待确认':'已确认'}</span></div>`}).join('')}</div>`:'老师还没有录入你的错题。'}
async function loadAccounts(){const r=await api('/api/users');$('#account-list').innerHTML=r.users.length?`<div class="row-list">${r.users.map(u=>`<div class="item"><div><b>${esc(u.realName||u.username)}</b><div class="meta">${esc(u.username)} · ${ROLE_NAMES[u.role]||esc(u.role)}${u.lastLoginAt?' · 最近登录 '+esc(u.lastLoginAt):''}</div></div>${u.username==='root'?'<span class="tag">内置管理员</span>':`<button onclick="resetPwd('${u.id}')">重置密码</button><button class="danger" onclick="delUser('${u.id}')">删除</button>`}</div>`).join('')}</div>`:'暂无账号。'}
window.resetPwd=async id=>{const p=prompt('请输入新密码（至少 6 位）');if(!p)return;try{await api(`/api/users/${id}/password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});toast('密码已重置')}catch(e){toast(e.message)}};
window.delUser=async id=>{if(!confirm('确定删除这个账号吗？'))return;try{await api(`/api/users/${id}`,{method:'DELETE'});await loadAccounts();toast('账号已删除')}catch(e){toast(e.message)}};
function renderSettings(){
 const groups={};settings.models.forEach(m=>{(groups[m.providerKey]??={provider:m.provider,models:[]}).models.push(m)});
 $('#provider-list').innerHTML=Object.entries(groups).map(([pk,g])=>`<div class="provider-card"><div class="provider-head"><b>${esc(g.provider)}</b><span class="key-badge ${settings.savedKeys?.[pk]?'saved':''}">${settings.savedKeys?.[pk]?'已保存 Key':'未保存 Key'}</span></div><div class="model-options">${g.models.map(m=>`<label class="${m.id===settings.model?'active':''}"><input type="radio" name="model-radio" value="${m.id}" ${m.id===settings.model?'checked':''}>${esc(m.label)}</label>`).join('')}</div><div class="provider-key-row"><input type="password" id="key-${pk}" placeholder="${settings.savedKeys?.[pk]?'已保存此厂商 Key（留空不覆盖）':'粘贴该厂商的 API Key'}" autocomplete="off"><button class="save-key" data-pk="${pk}">保存</button><button class="test-key" data-pk="${pk}">测试连接</button>${pk==='mimo'?'<button class="import-cc">从 CC Switch 导入</button>':''}</div><p class="test-msg" id="msg-${pk}"></p></div>`).join('');
 $('#provider-list').querySelectorAll('input[name=model-radio]').forEach(r=>r.onchange=async()=>{try{await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:r.value})});settings.model=r.value;renderSettings();toast('已切换模型')}catch(e){toast(e.message)}});
 $('#provider-list').querySelectorAll('.save-key').forEach(b=>b.onclick=async()=>{const pk=b.dataset.pk,key=$(`#key-${pk}`).value.trim();if(!key){toast('请先粘贴 API Key');return}const model=groups[pk].models.find(m=>m.id===settings.model)?.id||groups[pk].models[0].id;try{await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,apiKey:key})});$(`#key-${pk}`).value='';await refresh();toast('API Key 已保存')}catch(e){toast(e.message)}});
 $('#provider-list').querySelectorAll('.test-key').forEach(b=>b.onclick=async()=>{const pk=b.dataset.pk,msg=$(`#msg-${pk}`),model=groups[pk].models.find(m=>m.id===settings.model)?.id||groups[pk].models[0].id;try{b.disabled=true;b.textContent='测试中…';msg.textContent='';msg.className='test-msg';const r=await api('/api/models/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,apiKey:$(`#key-${pk}`).value})});msg.textContent='✓ 连接成功，模型回复：'+r.reply;msg.classList.add('test-ok')}catch(e){msg.textContent='✗ '+e.message;msg.classList.add('test-fail')}finally{b.disabled=false;b.textContent='测试连接'}});
 const importBtn=$('#provider-list .import-cc');if(importBtn)importBtn.onclick=async()=>{try{const r=await api('/api/cc-switch/import',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refresh();toast(`已从 CC Switch 导入小米 Key（${r.hint}）`)}catch(e){toast(e.message)}};
}
async function refresh(){if(currentUser?.role==='student'){data=await api('/api/data');renderStudent();return}[data,settings]=await Promise.all([api('/api/data'),api('/api/settings')]);render();renderSettings();renderSeats();renderAgent();loadAgents();if(currentUser?.role==='admin')loadAccounts()} async function del(type,id){if(confirm('确定删除这条记录吗？')){await api(`/api/${type}/${id}`,{method:'DELETE'});await refresh();toast('已删除')}}window.del=del;
function form(id,url,mapper){const f=$(id);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();try{const obj=Object.fromEntries(new FormData(f));await api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mapper?mapper(obj):obj)});f.reset();await refresh();toast('保存成功')}catch(err){toast(err.message)}})}
form('#class-form','/api/classes',x=>({...x,createdAt:new Date().toISOString()}));form('#student-form','/api/students');
$('#account-form').addEventListener('submit',async e=>{e.preventDefault();try{const obj=Object.fromEntries(new FormData(e.target));await api('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});e.target.reset();await loadAccounts();toast('账号已创建')}catch(err){toast(err.message)}});
$('#mistake-form').addEventListener('submit',async e=>{e.preventDefault();try{const obj=Object.fromEntries(new FormData(e.target));await api('/api/mistakes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});e.target.reset();await refresh();toast('错题已保存')}catch(err){toast(err.message)}});
async function uploadFiles(list){const paths=[];for(const f of [...list]){if(f.size>5*1024*1024)throw Error(`${f.name} 超过 5MB`);const src=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});paths.push((await api('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:src})})).path)}return paths}
$('#lesson-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#lesson-btn');const classId=$('#lesson-class').value,date=$('#lesson-date').value,period=$('#lesson-period').value;const clash=data.assignments.find(a=>a.classId===classId&&a.date===date&&String(a.period||'')===period);if(clash&&!confirm(`${date||'当天'}第${period||'?'}节已有「${className(classId)}」的《${clash.title}》，仍要再建一节课吗？`))return;try{const report=await uploadFiles($('#report-files').files),title=$('#lesson-title').value.trim();if(!report.length&&!title)throw Error('请上传课堂内容报告，或手动填写课程名称');btn.disabled=true;btn.textContent='保存中…';const lesson=await api('/api/lessons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classId,date,period,reportImages:report,title})});e.target.reset();$('#lesson-date').value=localDate();await refresh();$('#analyze-lesson').value=lesson.id;toast(`课程已保存：${lesson.title}`)}catch(err){toast(err.message)}finally{btn.disabled=false;btn.textContent='① 保存本节课'}});
$('#analyze-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#analyze-btn');const assignmentId=$('#analyze-lesson').value;if(!assignmentId){toast('请先选择所属课程（没有可先在第 1 步保存本节课）');return}try{if(!settings.hasApiKey)throw Error('请先在“设置”中填写 API Key');btn.disabled=true;btn.textContent='AI 正在识别与统计…';const work=await uploadFiles($('#work-files').files);const result=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignmentId,workImages:work})});e.target.reset();await refresh();$('#analyze-lesson').value=assignmentId;toast(`分析完成：已整理 ${result.mistakes.length} 条错题`);document.querySelector('[data-page="dashboard"]').click()}catch(err){toast(err.message)}finally{btn.disabled=false;btn.textContent='✦ 开始 AI 错题分析'}});
$('#seat-class').addEventListener('change',()=>{seatClass=$('#seat-class').value;selSeat=null;$('#seat-editor-body').style.display='none';$('#seat-editor-title').textContent='点击左侧座位开始记录';renderSeats()});
$('#seat-lesson').addEventListener('change',()=>{seatLesson=$('#seat-lesson').value;renderSeats()});
$('#seat-layout-btn').onclick=async()=>{if(!seatClass){toast('请先选择班级');return}try{await api('/api/seat-layout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classId:seatClass,rows:+$('#seat-rows').value,cols:+$('#seat-cols').value})});selSeat=null;$('#seat-editor-body').style.display='none';$('#seat-editor-title').textContent='点击左侧座位开始记录';await refresh();toast('座位布局已保存')}catch(e){toast(e.message)}};
$('#seat-student').addEventListener('change',async()=>{if(!selSeat)return;try{await api('/api/seats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classId:seatClass,row:selSeat.r,col:selSeat.c,studentId:$('#seat-student').value})});await refresh();toast('座位已更新')}catch(e){toast(e.message)}});
$('#seat-save').onclick=async()=>{if(!selSeat)return;const body={classId:seatClass,assignmentId:seatLesson,row:selSeat.r,col:selSeat.c,studentId:$('#seat-student').value,tags:[...$('#seat-tags').querySelectorAll('button.active')].map(b=>b.dataset.tag),note:$('#seat-note').value,workNote:$('#seat-work-note').value};if(seatDraftImage==='__clear__')body.clearImage=true;else if(seatDraftImage)body.image=seatDraftImage;try{await api('/api/performances',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});seatDraftImage='';await refresh();toast('课堂记录已保存')}catch(e){toast(e.message)}};
$('#seat-browse').onclick=()=>$('#paste-file').click();
$('#paste-file').addEventListener('change',()=>{const f=$('#paste-file').files[0];if(f){uploadSeatImage(f);$('#paste-file').value=''}});
$('#seat-work-note').addEventListener('paste',e=>{const f=[...(e.clipboardData?.files||[])].find(x=>x.type.startsWith('image/'));if(f){e.preventDefault();uploadSeatImage(f)}});
let agentList=[], agentCur='通用', agentChats={};
function chatOf(name){return agentChats[name]??={api:[],bubbles:[]}}
function renderAgent(){fillSelect('#agent-student',data.students,'请选择学生',x=>`${x.name} · ${className(x.classId)}`);fillSelect('#agent-lesson',[...data.assignments].reverse(),'请选择课程',x=>`${lessonLabel(x)} · ${x.title}`)}
function appendMsg(role,text){const d=document.createElement('div');d.className='msg '+role;d.textContent=text;const box=$('#agent-messages');box.appendChild(d);box.scrollTop=box.scrollHeight}
function agentMsg(role,text){chatOf(agentCur).bubbles.push({role,text});appendMsg(role,text)}
function downloadMd(filename,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
function appendDownloadBtn(filename,text){const d=document.createElement('div');d.className='msg bot';const b=document.createElement('button');b.className='dl-btn';b.textContent='⬇ 下载 MD 文档';b.onclick=()=>downloadMd(filename,text);d.appendChild(b);const box=$('#agent-messages');box.appendChild(d);box.scrollTop=box.scrollHeight}
function agentDownloadBtn(filename,text){chatOf(agentCur).bubbles.push({dl:[filename,text]});appendDownloadBtn(filename,text)}
function renderMd(md,baseUrl){
 let h=esc(md);
 h=h.replace(/!\[([^\]]*)\]\(([^)\s]+)\)/g,(m,a,s)=>`<img loading="lazy" src="${/^https?:|^data:/.test(s)?s:baseUrl+encodeURI(s)}" alt="${a}">`);
 h=h.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');
 h=h.replace(/^#### +(.*)$/gm,'<h4>$1</h4>').replace(/^### +(.*)$/gm,'<h3>$1</h3>').replace(/^## +(.*)$/gm,'<h2>$1</h2>').replace(/^# +(.*)$/gm,'<h1>$1</h1>');
 h=h.replace(/\*\*([^*\n]+)\*\*/g,'<b>$1</b>').replace(/`([^`\n]+)`/g,'<code>$1</code>');
 let out='',list=null;
 for(const ln of h.split('\n')){
  const ul=ln.match(/^\s*[-*] +(.*)/),ol=ln.match(/^\s*\d+\. +(.*)/);
  if(ul){if(list!=='ul'){out+=(list?`</${list}>`:'')+'<ul>';list='ul'}out+=`<li>${ul[1]}</li>`;continue}
  if(ol){if(list!=='ol'){out+=(list?`</${list}>`:'')+'<ol>';list='ol'}out+=`<li>${ol[1]}</li>`;continue}
  if(list){out+=`</${list}>`;list=null}
  out+=ln.trim()?(/^<h\d|^<img/.test(ln.trim())?ln:`<p>${ln}</p>`):'';
 }
 if(list)out+=`</${list}>`;
 return out;
}
function appendFileCard(f){const d=document.createElement('div');d.className='msg bot file-card';d.innerHTML=`<span class="file-name">📄 ${esc(f.name)}</span><span class="file-actions"><button type="button" class="dl-btn pv">预览</button><a class="dl-btn" href="${encodeURI(f.url)}" download="${esc(f.name)}">下载</a></span>`;d.querySelector('.pv').onclick=async()=>{try{const text=await (await fetch(encodeURI(f.url))).text();openMdModal(f.name,text,f.url.slice(0,f.url.lastIndexOf('/')+1))}catch(e){toast('读取文件失败')}};const box=$('#agent-messages');box.appendChild(d);box.scrollTop=box.scrollHeight}
function agentFileCard(f){chatOf(agentCur).bubbles.push({file:f});appendFileCard(f)}
function openMdModal(name,text,baseUrl){$('#md-modal-name').textContent=name;$('#md-modal-content').innerHTML=renderMd(text,baseUrl||'');$('#md-modal-dl').onclick=()=>downloadMd(name,text);$('#md-modal').classList.add('show')}
$('#md-modal-close').onclick=()=>$('#md-modal').classList.remove('show');
function renderChatHistory(){const box=$('#agent-messages');box.innerHTML='';const bs=chatOf(agentCur).bubbles;if(!bs.length){appendMsg('bot',`你好，我是「${agentCur}」智能体。可以直接问我学生的情况，或把课堂表现发给我润色；左侧选好学生和课程可生成完整学习总结。`);return}for(const b of bs){if(b.file)appendFileCard(b.file);else if(b.dl)appendDownloadBtn(...b.dl);else appendMsg(b.role,b.text)}}
function agentPickerFill(){const el=$('#agent-picker');if(!el)return;const old=el.value||agentCur;el.innerHTML=agentList.map(a=>`<option value="${esc(a.name)}">${esc(a.name)}${a.source==='mine'?'（我的）':''}</option>`).join('');el.value=[...el.options].some(o=>o.value===old)?old:'通用';agentCur=el.value||'通用'}
function renderAgentMgr(){const el=$('#agent-list');if(!el)return;el.innerHTML=agentList.map(a=>`<button type="button" class="agent-item ${a.name===agentCur?'active':''}" data-name="${esc(a.name)}">${esc(a.name)}<small>${a.source==='mine'?'我的':'通用'}</small></button>`).join('');el.querySelectorAll('.agent-item').forEach(b=>b.onclick=()=>openAgent(b.dataset.name))}
async function loadAgents(){if(currentUser?.role==='student')return;try{const r=await api('/api/agents');agentList=r.agents;const ms=$('#agent-model');if(ms&&ms.options.length<=1)ms.innerHTML='<option value="">跟随当前模型</option>'+settings.models.map(m=>`<option value="${m.id}">${esc(m.label)}</option>`).join('');renderAgentMgr();agentPickerFill();openAgent(agentCur)}catch(e){}}
async function openAgent(name){try{const r=await api(`/api/agents/${encodeURIComponent(name)}`);agentCur=name;let body=r.soul,model='';const m=r.soul.match(/^---\s*\n([\s\S]*?)\n---\s*\n/);if(m){body=r.soul.slice(m[0].length);const mm=m[1].match(/model:\s*(\S+)/);if(mm)model=mm[1]}if(document.activeElement!==$('#agent-soul'))$('#agent-soul').value=body;$('#agent-model').value=model;$('#agent-cur-name').textContent=name;$('#agent-cur-src').textContent=r.source==='mine'?'我的':'通用模板';renderAgentMgr();agentPickerFill()}catch(e){}}
$('#agent-soul-save').onclick=async()=>{const model=$('#agent-model').value,head=model?`---\nmodel: ${model}\n---\n`:'';try{await api(`/api/agents/${encodeURIComponent(agentCur)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({soul:head+$('#agent-soul').value})});toast(`智能体「${agentCur}」已保存`)}catch(e){toast(e.message)}};
$('#agent-new').onclick=async()=>{const name=prompt('新智能体名称（将从当前选中的智能体复制一份）');if(!name||!name.trim())return;try{await api('/api/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),from:agentCur})});await loadAgents();openAgent(name.trim());toast('已创建')}catch(e){toast(e.message)}};
$('#agent-delete').onclick=async()=>{if(!confirm(`删除智能体「${agentCur}」？（通用模板不受影响）`))return;try{await api(`/api/agents/${encodeURIComponent(agentCur)}`,{method:'DELETE'});agentCur='通用';await loadAgents();openAgent('通用');toast('已删除')}catch(e){toast(e.message)}};
$('#agent-picker').addEventListener('change',()=>{agentCur=$('#agent-picker').value;renderAgentMgr();renderChatHistory()});
$('#agent-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#agent-generate');const studentId=$('#agent-student').value,assignmentId=$('#agent-lesson').value;if(!studentId||!assignmentId){toast('请先选择学生和课程');return}try{btn.disabled=true;btn.textContent='Agent 正在分析截图与记录…';agentMsg('user',`生成 ${studentName(studentId)} 这节课的学习总结`);const r=await api('/api/agent/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId,assignmentId,agent:agentCur,savePath:$('#agent-path').value,extra:$('#agent-extra').value})});agentMsg('bot',r.markdown+`\n\n—— 已保存到：${r.path}`);const lesson=data.assignments.find(a=>a.id===assignmentId);agentDownloadBtn(`${studentName(studentId)}-${lesson?.date||localDate()}.md`,r.markdown);toast('总结已生成并保存')}catch(err){agentMsg('bot','生成失败：'+err.message);toast(err.message)}finally{btn.disabled=false;btn.textContent='✦ 生成并保存总结'}});
async function sendAgent(){const text=$('#agent-input').value.trim();if(!text)return;$('#agent-input').value='';agentMsg('user',text);const hist=chatOf(agentCur).api;hist.push({role:'user',content:text});$('#agent-send').disabled=true;try{const r=await api('/api/agent/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:hist,agent:agentCur,studentId:$('#agent-student').value,assignmentId:$('#agent-lesson').value})});hist.push({role:'assistant',content:r.reply});if(r.file){agentMsg('bot','总结已生成，文档如下，可预览或下载：');agentFileCard(r.file)}else{agentMsg('bot',r.reply)}}catch(err){agentMsg('bot','出错了：'+err.message)}finally{$('#agent-send').disabled=false}}
$('#agent-send').onclick=sendAgent;
$('#agent-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();sendAgent()}});
$('#tab-login').onclick=()=>{$('#tab-login').classList.add('active');$('#tab-register').classList.remove('active');$('#login-form').style.display='grid';$('#register-form').style.display='none'};
$('#tab-register').onclick=()=>{$('#tab-register').classList.add('active');$('#tab-login').classList.remove('active');$('#register-form').style.display='grid';$('#login-form').style.display='none'};
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();try{const obj=Object.fromEntries(new FormData(e.target));const r=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});setSession(r.token,r.user);e.target.reset();hideAuth();await refresh();toast(`欢迎回来，${r.user.realName||r.user.username}`)}catch(err){toast(err.message)}});
$('#register-form').addEventListener('submit',async e=>{e.preventDefault();try{const obj=Object.fromEntries(new FormData(e.target));if(obj.password!==obj.confirm)throw Error('两次输入的密码不一致');if(obj.role==='student'&&!obj.realName.trim())throw Error('学生注册需填写与班级名单一致的姓名');const r=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:obj.username,realName:obj.realName,password:obj.password,role:obj.role})});setSession(r.token,r.user);e.target.reset();hideAuth();await refresh();toast('注册成功，已自动登录')}catch(err){toast(err.message)}});
$('#logout-btn').onclick=()=>{token='';localStorage.removeItem('token');location.reload()};
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('show'));$('#'+b.dataset.page).classList.add('show');const n={dashboard:['班级学习总览','快速掌握全班的共性薄弱点'],import:['导入作业','先导入课堂报告，再分批导入学生作业'],seats:['课堂座位','点击座位，记录这个位置学生的课堂表现与做题情况'],agent:['总结 Agent','分析做题截图与错题，生成家长可读的学习总结'],classes:['班级与学生','创建班级；学生姓名也可由 AI 从作业中自动识别'],mistakes:['人工补充','仅在需要时补充或修正 AI 的分析结果'],accounts:['账号管理','创建、查看、重置或删除老师和学生账号'],settings:['设置','选择国内模型并配置本机 API Key']};$('#page-title').textContent=n[b.dataset.page][0];$('#subtitle').textContent=n[b.dataset.page][1]}));$('#quick-add').onclick=()=>document.querySelector('[data-page="import"]').click();$('#dashboard-class').addEventListener('change',e=>{dashboardClass=e.target.value;render()});$('#lesson-date').value=localDate();
async function init(){if(!token){showAuth();return}try{const me=await api('/api/auth/me');setSession(token,me.user);await refresh()}catch(e){if(token)toast('无法连接本地服务：'+e.message)}}
init();
